"""
scripts/figures.py — Generate all paper figures from experiment results.

Run after experiments.py. All figures saved to figures/ directory.
Every figure in the paper is generated by this script — no manual editing.

Usage:
    python scripts/figures.py
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
import json
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

ROOT       = Path(__file__).parent.parent
FIGURES    = ROOT / "figures"
RESULTS    = ROOT / "results"
FIGURES.mkdir(exist_ok=True)

# ── Plot style ────────────────────────────────────────────────────────────────
plt.rcParams.update({
    "font.family":       "serif",
    "font.size":         11,
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.grid":         True,
    "grid.alpha":        0.3,
    "figure.dpi":        150,
    "savefig.bbox_inches": "tight",
    "savefig.dpi":       300,
})

COLORS = {
    "global":     "#2166AC",   # blue — standard conformal
    "stratified": "#D6604D",   # red — proposed method
    "nominal":    "#1A9850",   # green — nominal coverage line
    "heat":       "#F46D43",   # orange — heat event highlight
    "neutral":    "#666666",
}

REGIME_COLORS = {
    "<75°F":    "#4393C3",
    "75-90°F":  "#92C5DE",
    "90-100°F": "#F4A582",
    ">100°F":   "#D6604D",
}


def load_results() -> dict:
    path = RESULTS / "experiment_log.json"
    if not path.exists():
        raise FileNotFoundError("Run scripts/experiments.py first.")
    with open(path) as f:
        return json.load(f)


def load_data() -> pd.DataFrame:
    from data.load import load_processed
    return load_processed()


# ═══════════════════════════════════════════════════════════════════════════════
# Figure 1: Coverage Degradation — Main Result
# ═══════════════════════════════════════════════════════════════════════════════

def fig1_coverage_degradation(results: dict):
    """
    Main paper figure. Shows empirical coverage by temperature regime
    for standard conformal vs. stratified conformal vs. nominal.
    """
    exp = results["experiments"]
    alpha = exp["conformal_standard"]["alpha"]
    nominal = 1 - alpha

    regimes = ["<75°F", "75-90°F", "90-100°F", ">100°F"]
    std_cov  = []
    strat_cov = []
    n_spikes  = []

    comparison = exp["conformal_stratified"]["coverage_comparison"]
    for r in regimes:
        if r in comparison:
            std_cov.append(comparison[r]["global_coverage"])
            strat_cov.append(comparison[r]["stratified_coverage"])
            n_spikes.append(comparison[r]["n_spikes"])
        else:
            std_cov.append(np.nan)
            strat_cov.append(np.nan)
            n_spikes.append(0)

    x = np.arange(len(regimes))
    width = 0.32

    fig, ax = plt.subplots(figsize=(8, 5))

    bars1 = ax.bar(x - width/2, std_cov,  width, label="Standard conformal",
                   color=COLORS["global"], alpha=0.85, edgecolor="white")
    bars2 = ax.bar(x + width/2, strat_cov, width, label="Stratified conformal (ours)",
                   color=COLORS["stratified"], alpha=0.85, edgecolor="white")

    # Nominal coverage line
    ax.axhline(nominal, color=COLORS["nominal"], linestyle="--", linewidth=1.8,
               label=f"Nominal coverage ({nominal:.0%})", zorder=5)

    # Annotate sample sizes
    for i, n in enumerate(n_spikes):
        if n > 0:
            ax.text(x[i], 0.02, f"n={n}", ha="center", va="bottom",
                    fontsize=8.5, color="white", fontweight="bold")

    ax.set_xticks(x)
    ax.set_xticklabels(regimes)
    ax.set_xlabel("Temperature Regime", fontweight="bold")
    ax.set_ylabel("Empirical Coverage", fontweight="bold")
    ax.set_title(
        "Figure 1: Conformal Coverage Degrades Under High Temperature\n"
        "Standard conformal fails in high-heat regimes; stratified calibration restores coverage",
        fontsize=10, pad=12
    )
    ax.set_ylim(0, 1.1)
    ax.axhspan(0, nominal - 0.05, alpha=0.04, color="red", label="Under-coverage zone")
    ax.legend(loc="lower left", fontsize=9)

    plt.tight_layout()
    path = FIGURES / "fig1_coverage_degradation.pdf"
    plt.savefig(path)
    plt.savefig(str(path).replace(".pdf", ".png"))
    print(f"  ✓ Figure 1 saved: {path.name}")
    plt.close()


# ═══════════════════════════════════════════════════════════════════════════════
# Figure 2: Calibration Curves
# ═══════════════════════════════════════════════════════════════════════════════

def fig2_calibration_curves(results: dict):
    """
    Reliability diagram. Empirical probability vs. predicted probability.
    Perfect calibration = diagonal. Shows overall miscalibration.
    """
    clf = results["experiments"]["classifier"]
    train_cal = clf["train"]["calibration_fraction_pos"]
    train_pred = clf["train"]["calibration_mean_pred"]
    test_cal  = clf["test"]["calibration_fraction_pos"]
    test_pred = clf["test"]["calibration_mean_pred"]

    fig, ax = plt.subplots(figsize=(6, 5))

    ax.plot([0, 1], [0, 1], "k--", linewidth=1.2, label="Perfect calibration", zorder=1)
    ax.plot(train_pred, train_cal, "o-", color=COLORS["global"], linewidth=2,
            markersize=6, label="Train (2021-22)", alpha=0.9)
    ax.plot(test_pred, test_cal,  "s-", color=COLORS["stratified"], linewidth=2,
            markersize=6, label="Test (2024)", alpha=0.9)

    ax.fill_between([0, 1], [0, 1], [0, 1], alpha=0.03, color="gray")
    ax.set_xlabel("Mean Predicted Probability (spike)", fontweight="bold")
    ax.set_ylabel("Empirical Fraction of Positives", fontweight="bold")
    ax.set_title(
        "Figure 2: Classifier Calibration Curve\n"
        "Deviation from diagonal = miscalibration",
        fontsize=10
    )
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)

    # Print AUROC in legend
    train_auroc = clf["train"]["auroc"]
    test_auroc  = clf["test"]["auroc"]
    ax.text(0.98, 0.05,
            f"Train AUROC = {train_auroc:.3f}\nTest AUROC  = {test_auroc:.3f}",
            transform=ax.transAxes, ha="right", va="bottom",
            fontsize=9, bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8))

    ax.legend(fontsize=9)
    plt.tight_layout()
    path = FIGURES / "fig2_calibration_curves.pdf"
    plt.savefig(path)
    plt.savefig(str(path).replace(".pdf", ".png"))
    print(f"  ✓ Figure 2 saved: {path.name}")
    plt.close()


# ═══════════════════════════════════════════════════════════════════════════════
# Figure 3: Feature Importance (SHAP-style bar chart)
# ═══════════════════════════════════════════════════════════════════════════════

def fig3_feature_importance(results: dict):
    """Horizontal bar chart of feature importances from GBM."""
    importances = results["experiments"]["classifier"]["feature_importances"]
    top_n = 12

    sorted_items = sorted(importances.items(), key=lambda x: x[1], reverse=True)[:top_n]
    features, values = zip(*sorted_items)

    # Clean feature names for publication
    name_map = {
        "lmp_zscore":      "LMP z-score (24h)",
        "lmp_lag1h":       "LMP lag 1h",
        "lmp_lag24h":      "LMP lag 24h",
        "lmp_roll24_mean": "LMP rolling mean (24h)",
        "lmp_roll24_std":  "LMP rolling std (24h)",
        "temp_f":          "Temperature (°F)",
        "temp_f_sq":       "Temperature² (nonlinear)",
        "heat_stress":     "Heat stress indicator (>95°F)",
        "temp_x_peak_hour":"Temp × peak hour",
        "hour":            "Hour of day",
        "solar_rad":       "Solar radiation",
        "wind_mph":        "Wind speed (mph)",
        "month":           "Month",
        "dow":             "Day of week",
        "is_summer":       "Summer indicator",
    }
    clean_names = [name_map.get(f, f) for f in features]

    fig, ax = plt.subplots(figsize=(7, 5))
    colors = [COLORS["heat"] if "temp" in f.lower() or "heat" in f.lower()
              else COLORS["global"] for f in features]

    bars = ax.barh(range(top_n), values[::-1] if False else values,
                   color=colors, alpha=0.85, edgecolor="white")
    ax.set_yticks(range(top_n))
    ax.set_yticklabels(clean_names, fontsize=9.5)
    ax.invert_yaxis()
    ax.set_xlabel("Feature Importance (GBM)", fontweight="bold")
    ax.set_title(
        "Figure 3: Feature Importances for Spike Classifier\n"
        "Orange = weather/temperature features",
        fontsize=10
    )

    # Add value labels
    for i, v in enumerate(values):
        ax.text(v + 0.001, i, f"{v:.3f}", va="center", fontsize=8)

    plt.tight_layout()
    path = FIGURES / "fig3_feature_importance.pdf"
    plt.savefig(path)
    plt.savefig(str(path).replace(".pdf", ".png"))
    print(f"  ✓ Figure 3 saved: {path.name}")
    plt.close()


# ═══════════════════════════════════════════════════════════════════════════════
# Figure 4: LMP Time Series with Conformal Intervals (Sept 2022 heat wave)
# ═══════════════════════════════════════════════════════════════════════════════

def fig4_heat_wave_timeline(df: pd.DataFrame, results: dict):
    """
    Timeline figure: LMP prices + temperature + conformal prediction
    during September 2022 heat wave. This is the 'money figure' of the paper.
    """
    # September 2022 heat wave: Sep 1-15
    heat_period = df[
        (df["datetime"].dt.year == 2022) &
        (df["datetime"].dt.month == 9) &
        (df["datetime"].dt.day <= 15)
    ].copy().sort_values("datetime")

    if len(heat_period) == 0:
        print("  ⚠ Figure 4: Sept 2022 data not in dataset (data might start later)")
        return

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 7), sharex=True,
                                    gridspec_kw={"height_ratios": [2, 1]})

    # Top panel: LMP with spike highlighting
    ax1.plot(heat_period["datetime"], heat_period["lmp"],
             color=COLORS["global"], linewidth=1.2, label="LMP ($/MWh)", zorder=3)

    # Highlight spikes
    spikes = heat_period[heat_period["spike"] == 1]
    ax1.scatter(spikes["datetime"], spikes["lmp"],
                color=COLORS["heat"], s=20, zorder=4, label="Price spike (top 5%)", alpha=0.8)

    # Threshold line
    threshold_price = heat_period["lmp"].quantile(0.95)
    ax1.axhline(threshold_price, color=COLORS["heat"], linestyle=":",
                alpha=0.6, label=f"95th percentile (${threshold_price:.0f})")

    ax1.set_ylabel("LMP ($/MWh)", fontweight="bold")
    ax1.legend(fontsize=8.5, loc="upper left")
    ax1.set_title(
        "Figure 4: California LMP and Temperature — September 2022 Heat Wave\n"
        "Extreme temperatures drive LMP spikes outside model training distribution",
        fontsize=10
    )

    # Bottom panel: Temperature
    ax2.fill_between(heat_period["datetime"], heat_period["temp_f"],
                     alpha=0.4, color=COLORS["heat"])
    ax2.plot(heat_period["datetime"], heat_period["temp_f"],
             color=COLORS["heat"], linewidth=1.5, label="Temperature (°F)")
    ax2.axhline(95, color="darkred", linestyle="--", linewidth=1,
                label="95°F threshold (heat stress)")
    ax2.axhline(105, color="darkred", linestyle=":", linewidth=1,
                label="105°F threshold (extreme heat)")

    ax2.set_xlabel("Date", fontweight="bold")
    ax2.set_ylabel("Temperature (°F)", fontweight="bold")
    ax2.legend(fontsize=8.5, loc="upper left")

    # Shade the peak heat event dates (Sep 5-9)
    for ax in [ax1, ax2]:
        ax.axvspan(
            pd.Timestamp("2022-09-05", tz="UTC"),
            pd.Timestamp("2022-09-09", tz="UTC"),
            alpha=0.12, color="red", label="_nolegend_"
        )

    plt.tight_layout()
    path = FIGURES / "fig4_heatwave_timeline.pdf"
    plt.savefig(path)
    plt.savefig(str(path).replace(".pdf", ".png"))
    print(f"  ✓ Figure 4 saved: {path.name}")
    plt.close()


# ═══════════════════════════════════════════════════════════════════════════════
# Figure 5: Covariate Shift Detection
# ═══════════════════════════════════════════════════════════════════════════════

def fig5_covariate_shift(df: pd.DataFrame, results: dict):
    """
    Show temperature distribution shift between training (2021-22) and test (2024).
    Visually motivates why conformal coverage degrades.
    """
    train_temp = df[df["year"].isin([2021, 2022])]["temp_f"].dropna()
    test_temp  = df[df["year"] == 2024]["temp_f"].dropna()

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4.5))

    # Left: KDE / histogram comparison
    bins = np.linspace(train_temp.min(), max(train_temp.max(), test_temp.max()), 40)
    ax1.hist(train_temp, bins=bins, density=True, alpha=0.55,
             color=COLORS["global"], label="Train (2021-22)")
    ax1.hist(test_temp, bins=bins, density=True, alpha=0.55,
             color=COLORS["stratified"], label="Test (2024)")
    ax1.axvline(95, color="darkred", linestyle="--", linewidth=1.5, label="95°F threshold")
    ax1.set_xlabel("Temperature (°F)", fontweight="bold")
    ax1.set_ylabel("Density", fontweight="bold")
    ax1.set_title("Temperature Distribution Shift\n(Train vs. Test)", fontsize=10)
    ax1.legend(fontsize=9)

    # Right: AUROC from shift detection experiment
    shift = results["experiments"]["covariate_shift"]
    auroc = shift["auroc_mean"]
    std   = shift["auroc_std"]

    ax2.barh(["Shift detector AUROC"], [auroc], xerr=[std],
             color=COLORS["global"] if auroc < 0.7 else COLORS["stratified"],
             alpha=0.85, capsize=6, height=0.4)
    ax2.axvline(0.5, color="gray", linestyle="--", linewidth=1.2, label="Random (0.5)")
    ax2.axvline(0.7, color="darkred", linestyle=":", linewidth=1.2,
                label="Strong shift threshold (0.7)")
    ax2.set_xlim(0.4, 1.0)
    ax2.set_xlabel("AUROC (weather features only)", fontweight="bold")
    ax2.set_title(
        f"Classifier-Based Shift Detection\n"
        f"AUROC = {auroc:.3f} ± {std:.3f} → {shift['interpretation']}",
        fontsize=10
    )
    ax2.legend(fontsize=9)

    fig.suptitle("Figure 5: Covariate Shift in Weather Features (2021-22 → 2024)",
                 fontsize=11, fontweight="bold", y=1.02)
    plt.tight_layout()
    path = FIGURES / "fig5_covariate_shift.pdf"
    plt.savefig(path)
    plt.savefig(str(path).replace(".pdf", ".png"))
    print(f"  ✓ Figure 5 saved: {path.name}")
    plt.close()


# ═══════════════════════════════════════════════════════════════════════════════
# Results Table (for paper)
# ═══════════════════════════════════════════════════════════════════════════════

def print_results_table(results: dict):
    """Print LaTeX-formatted results table for paper."""
    exp = results["experiments"]
    alpha = exp["conformal_standard"]["alpha"]
    nominal = 1 - alpha

    print("\n" + "="*70)
    print("RESULTS TABLE (paste into paper)")
    print("="*70)

    # Classifier metrics
    clf = exp["classifier"]
    print(f"\nClassifier Performance:")
    print(f"  Train AUROC: {clf['train']['auroc']:.3f} | Brier: {clf['train']['brier']:.4f}")
    print(f"  Test  AUROC: {clf['test']['auroc']:.3f}  | Brier: {clf['test']['brier']:.4f}")

    # Coverage table
    print(f"\nConformal Coverage (nominal = {nominal:.0%}, α = {alpha}):")
    print(f"{'Regime':<14} {'Global':>10} {'Stratified':>12} {'Δ':>8} {'n':>6}")
    print("-" * 54)
    comparison = exp["conformal_stratified"]["coverage_comparison"]
    for regime, data in comparison.items():
        if data:
            delta = data["delta"]
            sign = "+" if delta > 0 else ""
            print(f"{regime:<14} {data['global_coverage']:>10.3f} "
                  f"{data['stratified_coverage']:>12.3f} "
                  f"{sign}{delta:>7.3f} {data['n_spikes']:>6}")

    # Overall
    overall = exp["conformal_standard"]["coverage"]["empirical_coverage"]
    print(f"\nOverall empirical coverage: {overall:.3f} (nominal: {nominal:.2f})")

    # Shift detection
    shift = exp["covariate_shift"]
    print(f"\nCovariate Shift (weather features, 2021-22 → 2024):")
    print(f"  AUROC = {shift['auroc_mean']:.3f} ± {shift['auroc_std']:.3f}")
    print(f"  Interpretation: {shift['interpretation']}")

    print("\n" + "="*70)


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def fig6_vulnerability_coverage_matrix(results: dict):
    """
    The paper's equity contribution figure.

    2×4 heatmap: vulnerability level × temperature regime → empirical coverage.
    Shows whether coverage gap is larger for high-vulnerability communities.
    This is Figure 6 — the social science layer of the paper.
    """
    if "vulnerability" not in results["experiments"]:
        print("  ⚠ Figure 6: vulnerability experiment not run yet")
        return

    vuln_exp = results["experiments"]["vulnerability"]
    if "error" in vuln_exp:
        print(f"  ⚠ Figure 6: {vuln_exp['error']}")
        return

    matrix = vuln_exp["coverage_matrix"]
    nominal = 1 - results["experiments"]["conformal_standard"]["alpha"]

    regimes    = ["<75°F", "75-90°F", "90-100°F", ">100°F"]
    vuln_labels = ["Low vulnerability", "High vulnerability"]

    # Build coverage grid
    global_grid = np.full((2, 4), np.nan)
    strat_grid  = np.full((2, 4), np.nan)
    n_grid      = np.full((2, 4), 0)

    for vi, vl in enumerate(vuln_labels):
        if vl not in matrix:
            continue
        for ri, regime in enumerate(regimes):
            cell = matrix[vl].get(regime, {})
            if cell and cell.get("global_coverage") is not None:
                global_grid[vi, ri] = cell["global_coverage"]
                strat_grid[vi, ri]  = cell["stratified_coverage"]
                n_grid[vi, ri]      = cell.get("n_spikes", 0)

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    titles = ["Standard Conformal", "Stratified Conformal (Proposed)"]

    for ax, grid, title in zip(axes, [global_grid, strat_grid], titles):
        # Color: deviation from nominal (red = under-coverage, green = at/above)
        deviation = grid - nominal
        im = ax.imshow(deviation, cmap="RdYlGn", vmin=-0.3, vmax=0.3,
                       aspect="auto")

        ax.set_xticks(range(4))
        ax.set_xticklabels(regimes, fontsize=9.5)
        ax.set_yticks(range(2))
        ax.set_yticklabels(vuln_labels, fontsize=10)
        ax.set_title(title, fontweight="bold", fontsize=10)

        # Annotate cells
        for vi in range(2):
            for ri in range(4):
                val = grid[vi, ri]
                n   = n_grid[vi, ri]
                if not np.isnan(val):
                    color = "white" if abs(val - nominal) > 0.15 else "black"
                    ax.text(ri, vi, f"{val:.2f}\n(n={n})",
                            ha="center", va="center",
                            fontsize=8.5, color=color, fontweight="bold")
                else:
                    ax.text(ri, vi, "N/A", ha="center", va="center",
                            fontsize=8.5, color="gray")

        plt.colorbar(im, ax=ax, label="Coverage − Nominal", shrink=0.8)

    fig.suptitle(
        "Figure 6: Conformal Coverage by Vulnerability × Temperature Regime\n"
        f"Nominal coverage = {nominal:.0%}. Red = under-coverage, Green = at/above nominal.",
        fontsize=10, fontweight="bold", y=1.02
    )

    # Key finding annotation
    key = matrix.get("key_finding", {})
    disparity = key.get("coverage_disparity_extreme_heat")
    if disparity is not None:
        direction = "worse" if disparity > 0.02 else "comparable"
        fig.text(0.5, -0.04,
                 f"Coverage disparity (low vs high vuln, >100°F): {disparity:+.3f} "
                 f"→ High-vulnerability coverage is {direction} in extreme heat",
                 ha="center", fontsize=9, style="italic", color="darkred")

    plt.tight_layout()
    path = FIGURES / "fig6_vulnerability_coverage_matrix.pdf"
    plt.savefig(path)
    plt.savefig(str(path).replace(".pdf", ".png"))
    print(f"  ✓ Figure 6 saved: {path.name}")
    plt.close()


def fig7_vulnerability_map(results: dict):
    """
    California county-level energy burden bar chart
    (map requires geopandas — bar chart is portable substitute).
    Shows which counties are high/low vulnerability.
    """
    if "vulnerability" not in results["experiments"]:
        return
    vuln_exp = results["experiments"]["vulnerability"]
    if "error" in vuln_exp or "descriptive_stats" not in vuln_exp:
        return

    zone_summary = vuln_exp.get("zone_summary", {})
    high_counties = zone_summary.get("high_vuln_counties", [])
    low_counties  = zone_summary.get("low_vuln_counties", [])

    # Rebuild from synthetic data for visualization
    from data.vulnerability import load_vulnerability
    vuln_df = load_vulnerability()
    vuln_df = vuln_df.sort_values("energy_burden_pct", ascending=True)

    fig, ax = plt.subplots(figsize=(8, 7))
    colors = [REGIME_COLORS[">100°F"] if q == 5
              else REGIME_COLORS["90-100°F"] if q == 4
              else REGIME_COLORS["75-90°F"] if q == 3
              else REGIME_COLORS["<75°F"]
              for q in vuln_df["energy_burden_quintile"]]

    bars = ax.barh(range(len(vuln_df)), vuln_df["energy_burden_pct"],
                   color=colors, alpha=0.85, edgecolor="white")
    ax.set_yticks(range(len(vuln_df)))
    ax.set_yticklabels(vuln_df["county_name"], fontsize=9)
    ax.axvline(vuln_df["energy_burden_pct"].mean(), color="black",
               linestyle="--", linewidth=1.2, label=f"CA mean ({vuln_df['energy_burden_pct'].mean():.1f}%)")
    ax.set_xlabel("Energy Burden (% of household income)", fontweight="bold")
    ax.set_title(
        "Figure 7: Energy Burden by California County\n"
        "Darker = higher vulnerability quintile",
        fontsize=10
    )

    # Legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor=REGIME_COLORS["<75°F"],    label="Q1 (lowest burden)"),
        Patch(facecolor=REGIME_COLORS["75-90°F"],  label="Q2"),
        Patch(facecolor=REGIME_COLORS["90-100°F"], label="Q3-Q4"),
        Patch(facecolor=REGIME_COLORS[">100°F"],   label="Q5 (highest burden)"),
    ]
    ax.legend(handles=legend_elements, loc="lower right", fontsize=8.5)

    plt.tight_layout()
    path = FIGURES / "fig7_vulnerability_map.pdf"
    plt.savefig(path)
    plt.savefig(str(path).replace(".pdf", ".png"))
    print(f"  ✓ Figure 7 saved: {path.name}")
    plt.close()


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def generate_all_figures():
    print("Loading results and data...")
    results = load_results()

    try:
        df = load_data()
        has_data = True
    except Exception:
        print("  ⚠ Processed data not available — skipping data-dependent figures")
        has_data = False

    print("\nGenerating figures...")
    fig1_coverage_degradation(results)
    fig2_calibration_curves(results)
    fig3_feature_importance(results)

    if has_data:
        fig4_heat_wave_timeline(df, results)
        fig5_covariate_shift(df, results)

    fig6_vulnerability_coverage_matrix(results)
    fig7_vulnerability_map(results)

    print_results_table(results)
    print(f"\n✓ All figures saved to {FIGURES}/")


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent))
    generate_all_figures()
